version: "3.7"

x-shared-env-vars: &env-config rosmaster_configs.env
x-model-env-vars: &model-config model_configs.env

services:
    rosmaster:
        image: ros:melodic-ros-core
        container_name: rosmaster
        restart: unless-stopped
        network_mode: host
        env_file: *env-config
        command: stdbuf -o L roscore

    #################
    ## mission client ##
    #################

    mission-client-rosmaster:
        image: mission-client-ahv:latest
        depends_on:
            - rosmaster
        container_name: mission-grpc-client
        restart: unless-stopped
        network_mode: host
        env_file:
            - *env-config
            - *model-config
        environment:
            - ROS_DISTRO=melodic
        volumes:
            - ./map_param_files:/mount/client_configs
        command: roslaunch --wait client mission-client.launch
        tty: true


